version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: 8 - Build Automation & CI-CD with Jenkins/jenkins-exercises/Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
