pipeline {

    agent any

    tools {
        nodejs 'node'  // Specify the Node.js installation name configured in Jenkins
    }

    environment {
        DOCKERHUB_REPO = credentials('DOCKERHUB_REPO')
        DOCKERHUB_USERNAME = credentials('DOCKERHUB_USERNAME')
    }

    stages {
        stage('Increment Version') {
            steps {
                script {
                    // Increment the application version
                    // You can use a npm package like 'npm-version' or write a custom script to increment the version
                    // Example: sh 'npm run version:increment'
                    echo 'Increment the application version...'
                    dir ('app') {
                        def versionType = input(
                            id: 'versionType',
                            message: 'Select the version increment type:',
                            ok: 'Increment',
                            parameters: [
                                choice(
                                    name: 'type',
                                    choices: [
                                        'patch',
                                        'minor',
                                        'major'
                                    ],
                                    description: 'Version increment type'
                                )
                            ]
                        )
                        sh "npm version {$versionType}"
                        def packageJson = readJSON file: 'package.json'
                        def appVersion = packageJson.version
                        def buildNumber = env.BUILD_NUMBER
                        def imageVersion = "${appVersion}-${buildNumber}"
                        env.IMAGE_VERSION = imageVersion
                    }
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    // Run tests for the application
                    // Example: sh 'npm test'
                    echo 'Run tests for the application...'
                    dir('app') {
                        sh 'npm install'
                        catchError(buildResult:'FAILURE', stageResult: 'FAILURE'){
                            sh 'npm test' 
                            error "Tests failed. Please fix the failing tests and rerun the pipeline."
                        }  
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Build the Docker image with the incremented version
                    // Example: sh 'docker build -t myapp:${version} .'
                    echo 'Build the Docker image with the incremented version...'
                    sh "docker build -t ${DOCKERHUB_USERNAME}/${DOCKERHUB_REPO}:${env.IMAGE_VERSION} -f jenkins-exercises/Dockerfile ."
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    // Push the Docker image to a registry
                    // Example: sh 'docker push myapp:${version}'
                    echo 'Push the Docker image to a registry...'
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh "echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin"
                        sh "docker push ${DOCKERHUB_USERNAME}/${DOCKERHUB_REPO}:${env.IMAGE_VERSION}"
                    }
                }
            }
        }

        stage('Commit Version') {
            steps {
                script {
                    // Commit the version increment to Git
                    // Example:
                    // sh 'git add package.json'
                    // sh 'git commit -m "Increment version to ${version}"'
                    // sh 'git push origin main'
                    echo 'Commit the version increment to Git...'
                    sh 'git config --global user.email "jenkins@example.com"'
                    sh 'git config --global user.name "Jenkins"'
                    withCredentials([usernamePassword(credentialsId: 'github-credentials', usernameVariable: 'GITHUB_USERNAME', passwordVariable: 'GITHUB_PASSWORD')]) {
                        sh "git remote set-url origin https://${GITHUB_USERNAME}:${GITHUB_PASSWORD}@github.com/your-username/your-repository.git"
                        dir('app') {
                            sh 'git add package.json'
                        }
                        sh "git commit -m 'Update version to ${env.IMAGE_VERSION}'"
                        sh 'git push origin HEAD:main'
                    }
                }
            }
        }
    }
}