version: '3'
services:
  mysql-container:
    image: mysql:latest
    restart: always
    env_file:
      - db_credentials.env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  
  phpmyadmin-container:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8082:80"
    depends_on:
      - mysql-container
      - app
    environment:
      PMA_HOST: mysql-container

  app:
    image: java-app:1.0
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql-container
    env_file:
      - app_credentials.env
    environment:
      DB_SERVER: mysql-container
      DB_PORT: 3306

volumes:
    db_data: