version: '3.8'
services:
  mysql-container:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin-container:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8082:80"
    depends_on:
      - mysql-container
      - app
    environment:
      PMA_HOST: mysql-container
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  app:
    image: 138.197.7.3:8083/java-app:1.1
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql-container
    environment:
      DB_SERVER: mysql-container
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PWD: ${MYSQL_PASSWORD}

volumes:
  db_data: