version: '3'
services:
  mysql-conatiner:
    image: mysql:latest
    restart: always
    env_file:
      - db_credentials.env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  
  phpmyadmin-container:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8082:80"
    depends_on:
      - db

volumes:
    db_data: