version: '3'
services:
  db:
    image: mysql:latest
    container_name: mysql-conatiner
    restart: always
    env_file:
      - db_credentials.env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-container
    restart: always
    ports:
      - "8082:80"
    depends_on:
      - db

volumes:
    db_data: